// AUTOGENERATED FILE: rpcx server stub code
// compilable during generation.

package main

import (
	"brianGo/web/rpcx/raw"
	"flag"
	"github.com/rcrowley/go-metrics"
	"github.com/smallnest/rpcx/server"
	"github.com/smallnest/rpcx/serverplugin"
	"time"
)

var (
	addr     = flag.String("addr", "localhost:8972", "server address")
	basePath = flag.String("base", "/rpcx", "prefix path")
)

func main() {
	flag.Parse()

	_ = time.Second
	_ = metrics.UseNilMetrics
	_ = serverplugin.GetFunctionName

	s := server.NewServer()
	addRegistryPlugin(s)

	registerServices(s)

	s.Serve("tcp", *addr)
}
func registerServices(s *server.Server) {
	s.RegisterName("Arith", new(raw.Arith), "")
	s.RegisterName("Echo", new(raw.Echo), "")
	s.RegisterName("TimeS", new(raw.TimeS), "")
	//s.Register(new(raw.TimeS), "")
}
func addRegistryPlugin(s *server.Server) {

}
